[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "fast-funcs"
version = "0.1.0"
description = "Drop-in replacements for Python's built-in functions with better performance, lower overhead, and specialized optimizations"
readme = "README.md"
requires-python = ">=3.10"
license = "Unlicense"
authors = [
    {name = "Fkernel653"}
]

[project.optional-dependencies]
dev = ["ruff", "uv"]

[tool.uv.build-backend]
module-root = ""
