[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "pathlib-ng"
version = "0.1.0"
description = "A lightweight, drop-in replacement for `pathlib.Path` with enhanced features, better error messages, and zero external dependencies"
readme = "README.md"
requires-python = ">=3.6"
license = "Unlicense"
authors = [
    {name = "Fkernel653"}
]

[project.optional-dependencies]
dev = ["ruff", "uv"]

[tool.uv.build-backend]
module-root = ""
